ConnectCareApp/Controllers/Api/ConnectCareSponsorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ConnectCareApp.DataAccess.Data;
using ConnectCareApp.Models.Entity;

namespace ConnectCareApp.Controllers.Api
{
    [Route("api/[controller]")]
    [ApiController]
    public class ConnectCareSponsorsController : ControllerBase
    {
        private readonly ApplicationDbContext _context;

        public ConnectCareSponsorsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: api/ConnectCareSponsors
        [HttpGet]
        public IEnumerable<ConnectCareSponsor> GetConnectCareSponsors(string userName)
        {
            return _context.ConnectCareSponsors.Where(x=>x.UserName==userName);
        }

        // GET: api/ConnectCareSponsors/5
        [HttpGet("{id}")]
        public async Task<IActionResult> GetConnectCareSponsor([FromRoute] int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var connectCareSponsor = await _context.ConnectCareSponsors.FindAsync(id);

            if (connectCareSponsor == null)
            {
                return NotFound();
            }

            return Ok(connectCareSponsor);
        }

        // PUT: api/ConnectCareSponsors/5
        [HttpPut("{id}")]
        public async Task<IActionResult> PutConnectCareSponsor([FromRoute] int id, [FromBody] ConnectCareSponsor connectCareSponsor)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != connectCareSponsor.Id)
            {
                return BadRequest();
            }

            _context.Entry(connectCareSponsor).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ConnectCareSponsorExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/ConnectCareSponsors
        [HttpPost]
        public async Task<IActionResult> PostConnectCareSponsor([FromBody] ConnectCareSponsor connectCareSponsor)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            _context.ConnectCareSponsors.Add(connectCareSponsor);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetConnectCareSponsor", new { id = connectCareSponsor.Id }, connectCareSponsor);
        }

        // DELETE: api/ConnectCareSponsors/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteConnectCareSponsor([FromRoute] int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var connectCareSponsor = await _context.ConnectCareSponsors.FindAsync(id);
            if (connectCareSponsor == null)
            {
                return NotFound();
            }

            _context.ConnectCareSponsors.Remove(connectCareSponsor);
            await _context.SaveChangesAsync();

            return Ok(connectCareSponsor);
        }

        private bool ConnectCareSponsorExists(int id)
        {
            return _context.ConnectCareSponsors.Any(e => e.Id == id);
        }
    }
}

ConnectCareApp/Controllers/ConnectCareBeneficiariesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ConnectCareApp.DataAccess.Data;
using ConnectCareApp.Models.Entity;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Hosting.Internal;
using ConnectCareApp.ViewModel;
using System.IO;

namespace ConnectCareApp.Controllers
{
    public class ConnectCareBeneficiariesController : Controller
    {
        private readonly ApplicationDbContext _context;
       
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly HostingEnvironment _hostingEnvironment;
        public ConnectCareBeneficiariesController(ApplicationDbContext context, SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager, HostingEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
        }


        // GET: ConnectCareBeneficiaries
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.ConnectCareBeneficiaries.Include(c => c.ConnectCareSponsor);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: ConnectCareBeneficiaries/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var connectCareBeneficiary = await _context.ConnectCareBeneficiaries
                .Include(c => c.ConnectCareSponsor)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (connectCareBeneficiary == null)
            {
                return NotFound();
            }

            return View(connectCareBeneficiary);
        }

        // GET: ConnectCareBeneficiaries/Create
        public async Task<IActionResult> Create()
        {
            var model = new BeneficiaryCreateVm();
            var user = await _userManager.GetUserAsync(User);
            ViewData["ConnectCareSponsorId"] = new SelectList(_context.ConnectCareSponsors.Where(x => x.Email == user.Email), "Id", "UserName");

            return View(model);
        }

        // POST: ConnectCareBeneficiaries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BeneficiaryCreateVm model)
        {
            var user = await _userManager.GetUserAsync(User);
            if (ModelState.IsValid)
            {
                var Beneficiary = new ConnectCareBeneficiary
                {
                    Id = model.Id,
                    Firstname=model.Firstname,
                    UserName = model.UserName,
                    Gender = model.Gender,
                    State = model.State,
                    Country = model.Country,
                    City = model.City,
                    Address = model.Address,
                    Email = model.Email,
                    Phonenumber = model.Phonenumber,
                    Relationship = model.Relationship,
                    Age = model.Age,
                    Lastname = model.Lastname,
                    CreatedOn = model.CreatedOn,
                    BeneficiaryCat = model.BeneficiaryCat,
                    Dob=model.Dob,
                    Lga=model.Lga,
                    GuardianPhonenumber=model.GuardianPhonenumber,
                    GuardianEmail=model.GuardianEmail,
                    SuggestedProvider=model.SuggestedProvider,
                    SuggestedPlan=model.SuggestedPlan,
                    PolicyNumber=model.PolicyNumber,
                    VerificationStatus=model.VerificationStatus,
                    Active=model.Active,
                    Status=model.Status,
                    Category=model.Category,
                    Addon=model.Addon,
                    Administeredby=model.Administeredby,
                    AdministrationDate=model.AdministrationDate,
                    ConnectCareSponsorId=model.ConnectCareSponsorId,
                    Fullname=model.FullName
                };
                if (model.ImageUrl != null && model.ImageUrl.Length > 0)
                {
                    var uploadDir = @"images/sponsor";
                    var fileName = Path.GetFileNameWithoutExtension(model.ImageUrl.FileName);
                    var extension = Path.GetExtension(model.ImageUrl.FileName);
                    var webRootPath = _hostingEnvironment.WebRootPath;
                    fileName = DateTime.UtcNow.ToString("yymmssfff") + fileName + extension;
                    var path = Path.Combine(webRootPath, uploadDir, fileName);
                    await model.ImageUrl.CopyToAsync(new FileStream(path, FileMode.Create));
                    Beneficiary.ImageUrl = "/" + uploadDir + "/" + fileName;
                }
                _context.Add(Beneficiary);
                await _context.SaveChangesAsync();
                return RedirectToAction("Info", "ConnectCareSponsors");
            }
            ViewData["ConnectCareSponsorId"] = new SelectList(_context.ConnectCareSponsors.Where(x => x.Email == user.Email), "Id", "UserName", model.ConnectCareSponsorId);
            return View(model);
          
        }

        // GET: ConnectCareBeneficiaries/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var user = await _userManager.GetUserAsync(User);
            if (id == null)
            {
                return NotFound();
            }

            var connectCareBeneficiary = await _context.ConnectCareBeneficiaries.FindAsync(id);
            if (connectCareBeneficiary == null)
            {
                return NotFound();
            }
            var model = new BeneficiaryEditVm()
            {
                Id = connectCareBeneficiary.Id,
                Firstname = connectCareBeneficiary.Firstname,
                UserName = connectCareBeneficiary.UserName,
                Gender = connectCareBeneficiary.Gender,
                State = connectCareBeneficiary.State,
                Country = connectCareBeneficiary.Country,
                City = connectCareBeneficiary.City,
                Address = connectCareBeneficiary.Address,
                Email = connectCareBeneficiary.Email,
                Phonenumber = connectCareBeneficiary.Phonenumber,
                Relationship = connectCareBeneficiary.Relationship,
                Age = connectCareBeneficiary.Age,
                Lastname = connectCareBeneficiary.Lastname,
                CreatedOn = connectCareBeneficiary.CreatedOn,
                BeneficiaryCat = connectCareBeneficiary.BeneficiaryCat,
                Dob = connectCareBeneficiary.Dob,
                Lga = connectCareBeneficiary.Lga,
                GuardianPhonenumber = connectCareBeneficiary.GuardianPhonenumber,
                GuardianEmail = connectCareBeneficiary.GuardianEmail,
                SuggestedProvider = connectCareBeneficiary.SuggestedProvider,
                SuggestedPlan = connectCareBeneficiary.SuggestedPlan,
                PolicyNumber = connectCareBeneficiary.PolicyNumber,
                VerificationStatus = connectCareBeneficiary.VerificationStatus,
                Active = connectCareBeneficiary.Active,
                Status = connectCareBeneficiary.Status,
                Category = connectCareBeneficiary.Category,
                Administeredby = connectCareBeneficiary.Administeredby,
                AdministrationDate = connectCareBeneficiary.AdministrationDate,
                ConnectCareSponsorId = connectCareBeneficiary.ConnectCareSponsorId
               
             
            };
            ViewData["ConnectCareSponsorId"] = new SelectList(_context.ConnectCareSponsors.Where(x => x.Email == user.Email), "Id", "UserName", model.ConnectCareSponsorId);
            return View(model);
        }

        // POST: ConnectCareBeneficiaries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(BeneficiaryEditVm model)
        {
            var user = await _userManager.GetUserAsync(User);

            if (ModelState.IsValid)
            {
                var connectCareBeneficiary = await _context.ConnectCareBeneficiaries.FindAsync(model.Id);
                if (connectCareBeneficiary == null)
                {
                    return NotFound();
                }


                connectCareBeneficiary.Id = model.Id;              
                connectCareBeneficiary.Firstname=model.Firstname;
                connectCareBeneficiary.UserName=model.UserName;
                connectCareBeneficiary.Gender = model.Gender;
                connectCareBeneficiary.State = model.State;
                connectCareBeneficiary.Country = model.Country;
                connectCareBeneficiary.City = model.City;
                connectCareBeneficiary.Address = model.Address;
                connectCareBeneficiary.Email = model.Email;
                connectCareBeneficiary.Phonenumber = model.Phonenumber;
                connectCareBeneficiary.Relationship = model.Relationship;
                connectCareBeneficiary.Age = model.Age;
                connectCareBeneficiary.Lastname = model.Lastname;
                connectCareBeneficiary.CreatedOn = model.CreatedOn;

ConnectCareApp/Views/ConnectCareSponsors/BeneficiaryCount.cshtml
@model IEnumerable<ConnectCareApp.Models.Entity.ConnectCareBeneficiary>

@{
    ViewData["Title"] = "BeneficiaryCount";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>BeneficiaryCount</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Fullname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.State)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Phonenumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Relationship)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sponsorid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedOn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UpdatedOn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsDeleted)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SiteId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BeneficiaryCat)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Passport)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BeneficiaryId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Firstname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Dob)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lastname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lga)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GuardianPhonenumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GuardianEmail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SuggestedProvider)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SuggestedPlan)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PolicyNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VerificationStatus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Active)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Addon)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Administeredby)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AdministrationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sponsoridstring)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ConnectCareSponsor)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Fullname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phonenumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Relationship)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sponsorid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedOn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UpdatedOn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsDeleted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SiteId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BeneficiaryCat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Passport)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BeneficiaryId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Firstname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dob)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lastname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lga)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GuardianPhonenumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GuardianEmail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SuggestedProvider)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SuggestedPlan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PolicyNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VerificationStatus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Active)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Addon)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Administeredby)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AdministrationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sponsoridstring)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ConnectCareSponsor.Id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

ConnectCareApp/Views/ConnectCareSponsors/Details.cshtml
@model ConnectCareApp.Models.Entity.ConnectCareSponsor

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}
<!-- Card -->
<!-- Card -->

<div class="col-md-12 text-center">

    <a asp-action="Info" asp-route-id="@Model.Id" class="btn btn-primary">List of Beneficiaries</a>
    <br /><br />
</div>
<div class="col-md-12 mb-4">


    <!--Card-->
    <div class="card">

        <!--Card content-->
        <div class="card-body">

            <table class="table table-bordered table-striped">

                <tbody>
                    <tr>
                        <td class="dec"> @Html.DisplayNameFor(model => model.Firstname)</td>
                        <td class="dec"> @Html.DisplayFor(model => model.Firstname)</td>
                    </tr>
                    <tr>
                        <td class="dec">@Html.DisplayNameFor(model => model.Gender)</td>
                        <td class="dec"> @Html.DisplayFor(model => model.Gender)</td>
                    </tr>
                    <tr>
                        <td class="dec"> @Html.DisplayNameFor(model => model.Occupation)</td>
                        <td class="dec"> @Html.DisplayFor(model => model.Occupation)</td>
                    </tr>
                    <tr>
                        <td class="dec">  @Html.DisplayNameFor(model => model.Country)</td>
                        <td class="dec">  @Html.DisplayFor(model => model.Country)</td>
                    </tr>
                    <tr>
                        <td class="dec">  @Html.DisplayNameFor(model => model.State)</td>
                        <td class="dec">  @Html.DisplayFor(model => model.State)</td>
                    </tr>
                    <tr>
                        <td class="dec">@Html.DisplayNameFor(model => model.Address)</td>
                        <td class="dec">@Html.DisplayFor(model => model.Address)</td>
                    </tr>
                    <tr>
                        <td class="dec">@Html.DisplayNameFor(model => model.Email)</td>
                        <td class="dec">@Html.DisplayFor(model => model.Email)</td>
                    </tr>
                    <tr>
                        <td class="dec"> @Html.DisplayNameFor(model => model.Phonenumber)</td>
                        <td class="dec"> @Html.DisplayFor(model => model.Phonenumber)</td>
                    </tr>



                </tbody>
            </table>

        </div>


    </div>
    <!--/.Card-->

</div>

ConnectCareApp/Views/ConnectCareSponsors/Info.cshtml
@model IEnumerable<ConnectCareApp.Models.Entity.ConnectCareBeneficiary>

@{
    ViewData["Title"] = "Info";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}




<!-- Table with panel -->
<div class="card card-cascade narrower">

    <!--Card image-->
    <div class="view view-cascade gradient-card-header blue-gradient narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center">

        <p>
            <a class=" btn btn-outline-primary">Create New</a>
        </p>

        <a href="#" class="white-text mx-3">List of Beneficiaries</a>

        
        <h4 class="text-info"></h4> 
        

    </div>
    <!--/Card image-->

    <div class="px-4">

        <div class="table-wrapper">
            <!--Table-->
            <table class="table table-hover mb-0 table-responsive">

                <!--Table head-->
                <thead>
                    <tr>

                        <th>
                            @Html.DisplayNameFor(model => model.Fullname)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Firstname)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.Lastname)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.UserName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Gender)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Country)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.State)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Address)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.Email)
                        </th>
                       
                        <th>
                            @Html.DisplayNameFor(model => model.Phonenumber)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.ImageUrl)
                        </th>

                        <th>
                            @Html.DisplayNameFor(model => model.Relationship)
                        </th>

                      

                        <th>
                            @Html.DisplayNameFor(model => model.Lga)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.SuggestedProvider)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.SuggestedPlan)
                        </th>

                        <th>Actions</th>
                        <th></th>
                    </tr>
                </thead>
                <!--Table head-->
                <!--Table body-->
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Fullname)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Firstname)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Lastname)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.UserName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Gender)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Country)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.State)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.Address)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>
                       
                        <td>
                            @Html.DisplayFor(modelItem => item.Phonenumber)
                        </td>
                        <td>
                            <img alt="nil" src="@Url.Content(item.ImageUrl)" width="120" height="70" class="rounded" />
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Relationship)
                        </td>
                        
                        <td>
                            @Html.DisplayFor(modelItem => item.Lga)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SuggestedProvider)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SuggestedPlan)
                        </td>


                        <td>
                            <a asp-controller="ConnectCareBeneficiaries" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-indigo btn-sm m-0">Edit</a>

                        </td>
                    
                        <td>
                            <a asp-controller="ConnectCareBeneficiaries" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm m-0">Delete</a>
                        </td>
                    </tr>
                    }

                </tbody>
                <!--Table body-->
            </table>
            <!--Table-->
        </div>

    </div>

</div>
<!-- Table with panel -->

ConnectCareApp/Views/ConnectCareSponsors/NoRecords.cshtml
@{
    ViewData["Title"] = "NoRecords";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

    <div class="col-md-12 mb-4">

        <br />
        <!--Card-->
       

            <!--Card content-->
         

        <div class="card card-cascade narrower">

            <!--Card image-->






            <div class="text-center">
                <a href="#" class="text-info mx-3">Please follow the link below to create a sponsor and a beneficiary, You don't have any !</a>
            </div>
            <div class="text-center">
                <p>
                    <a asp-action="Create" class=" btn btn-outline-primary text-center">Create New</a>
                </p>
            </div>

            <!--/Card image-->



        </div>

        


      
        <!--/.Card-->

    </div>